#!/bin/bash

# Bail if any statement returns non-zero
set -o errexit
# Bail if unset variable is accessed
set -o nounset
# Pipelines exit with rightmost non-zero exit code, or zero if fully successful
set -o pipefail

scriptdir="$(dirname "$(readlink -f "$0")")"
if [[ -n "${1-}" ]]; then
    source_hooks_path="$1"
else
    source_hooks_path="$(readlink -f "$scriptdir/hooks")"
fi

config_repo_path="$(git rev-parse --show-toplevel)"

dest_hooks_path="$config_repo_path/.git/hooks"

if [[ "$(basename "$config_repo_path")" != "config" ]] && [[ "$(basename "$config_repo_path")" != "gbt_config" ]]; then
    echo "Must be run from within a gbtconfig repository! Current repo: $config_repo_path" >&2
    exit 1
fi

for source_file in $(find "$source_hooks_path" -maxdepth 1 -type f); do
    dest_file="$dest_hooks_path/$(basename "$source_file")"
    if [[ -e "$dest_file" ]]; then
        echo rm "$dest_file"
        if [[ -z "${DRYRUN-}" ]]; then
            rm "$dest_file"
        fi
    fi
    echo ln -s "$source_file" "$dest_file"
    if [[ -z "${DRYRUN-}" ]]; then
        ln -s "$source_file" "$dest_file"
    fi
done
