#!/bin/bash

# Bail if any statement returns non-zero
set -o errexit
# Bail if unset variable is accessed
set -o nounset
# Pipelines exit with rightmost non-zero exit code, or zero if fully successful
set -o pipefail

if [[ -n "${1-}" ]]; then
    installation_directory="$1"
else
    installation_directory=/home/gbt1/gbt_config_warden/hooks
fi

current_dir="$(basename "$(pwd)")"

scriptdir="$(dirname "$(readlink -f "$0")")"
config_repo_path="$(git rev-parse --show-toplevel)"
dest_hook_path="$config_repo_path/.git/hooks"

if [[ "$(basename "$config_repo_path")" != "config" ]] && [[ "$(basename "$config_repo_path")" != "gbt_config" ]]; then
    echo "Must be run from within a gbtconfig repository!" >&2
    exit 1
fi

for source_file in $(find "$installation_directory" -maxdepth 1 -type f); do
    dest_file="$dest_hook_path/$(basename "$source_file")"
    if [[ -e "$dest_file" ]]; then
        echo rm "$dest_file"
        if [[ -z "${DRYRUN-}" ]]; then
            rm "$dest_file"
        fi
    fi
    echo ln -s "$source_file" "$dest_file"
    if [[ -z "${DRYRUN-}" ]]; then
        ln -s "$source_file" "$dest_file"
    fi
done
