#!/bin/bash

scriptdir="$(dirname "$(readlink -f "$0")")"
if [[ -z "$1" ]]; then
    echo "usage: install_gbt_release_warden PATH" >&2
    exit 1
fi

if [[ -e "$1"/.git ]]; then
    echo "git repo already exists in $1; bailing out" >&2
    exit 1
fi

if [[ "$USER" != "monctrl" ]]; then
	echo "Must run as monctrl" >&2
	exit 1
fi

cd "$1"

echo Initializing git repo
git init

echo Copying files to "$1"...
rsync -av "$scriptdir"/gbt_release_warden_template/ "$1"

echo "Staging all files (will take a little while)"
git add -A

echo "Creating initial commit"
git commit -m 'Initial commit'
